name:                difftime
version:             0.1.0.0
github:              "jmdaemon/difftime"
license:             MIT
author:              "Joseph Diza"
maintainer:          "josephm.diza@gmail.com"
copyright:           "2022 Joseph Diza"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jmdaemon/difftime#readme>

dependencies:
- base >= 4.7 && < 5
- regex-tdfa ^>= 1.3.1
- optparse-applicative
#- optparse-applicative ^>= 0.16.1

library:
  source-dirs: src

executables:
  difftime-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - difftime

tests:
  difftime-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - difftime
